import os
import time
import requests
import base64

def create_pull_request(repo_url: str, file_path: str, patched_content: str, finding: dict, condition: str) -> dict:
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN not set")

    # Extract owner/repo from URL
    # https://github.com/owner/repo.git -> owner/repo
    repo_path = repo_url.replace("https://github.com/", "").replace(".git", "")
    
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    base_url = f"https://api.github.com/repos/{repo_path}"

    # Get default branch
    repo_info = requests.get(base_url, headers=headers).json()
    default_branch = repo_info.get("default_branch", "main")

    # Get latest commit SHA of default branch
    branch_info = requests.get(f"{base_url}/branches/{default_branch}", headers=headers).json()
    base_sha = branch_info["commit"]["sha"]

    # Create new branch name
    rule_short = finding["rule_id"].split(".")[-1][:20]
    new_branch = f"autofix/{condition}-{rule_short}-L{finding['line']}-{int(time.time())}"

    # Create new branch
    requests.post(f"{base_url}/git/refs", headers=headers, json={
        "ref": f"refs/heads/{new_branch}",
        "sha": base_sha
    })

    # Get file SHA for update
    relative_path = file_path.split("/", file_path.count("/") - 1)[-1]
    # Try to get the file from repo
    file_info = requests.get(f"{base_url}/contents/{relative_path}", headers=headers, params={"ref": new_branch})
    file_sha = file_info.json().get("sha") if file_info.status_code == 200 else None

    # Encode content
    encoded = base64.b64encode(patched_content.encode()).decode()

    # Commit patched file to new branch
    commit_payload = {
        "message": f"fix({condition}): auto-patch {rule_short} in {os.path.basename(file_path)}",
        "content": encoded,
        "branch": new_branch
    }
    if file_sha:
        commit_payload["sha"] = file_sha

    requests.put(f"{base_url}/contents/{relative_path}", headers=headers, json=commit_payload)

    # Create pull request
    pr_response = requests.post(f"{base_url}/pulls", headers=headers, json={
        "title": f"[AutoFix/{condition.upper()}] {finding['message'][:60]}",
        "body": f"""## Automated Security Patch

**Vulnerability:** {finding['message']}
**Rule:** {finding['rule_id']}
**File:** {os.path.basename(file_path)}
**Line:** {finding['line']}
**Prompt Condition:** {condition}

### Vulnerable Code
```python
{finding['code_snippet']}
```

*This PR was automatically generated by Intelligent CI/CD.*
""",
        "head": new_branch,
        "base": default_branch
    })

    pr_data = pr_response.json()
    return {
        "pr_url": pr_data.get("html_url"),
        "pr_number": pr_data.get("number"),
        "branch": new_branch
    }
